title = 'Learn with AI'
theme = 'hugo-graphy'
baseURL = "https://learninfun.github.io/learn-with-ai/"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

# English is the default language
defaultContentLanguage = "en"
# Force to have /en/my-page and /fr/my-page routes, even for default language.
defaultContentLanguageInSubdir= true

[Languages]
  [Languages.en]
    contentDir = "content/english"
    landingPageURL = "/learn-with-ai"
    title = "Learn with AI"
    weight = 1
    languageName = "English"
  [Languages.zh-cn]
    contentDir = "content/zh-cn"
    landingPageURL = "/learn-with-ai/zh-cn"
    title = "Learn with AI"
    weight = 2
    languageName = "簡體中文"
  [Languages.zh-tw]
    contentDir = "content/zh-tw"
    landingPageURL = "/learn-with-ai/zh-tw"
    title = "Learn with AI"
    weight = 3
    languageName = "繁體中文"



[params]
  ordersectionsby = "weight"
  themeVariant = "blue"
  disablePathToLower = true

[markup.goldmark]
  [markup.goldmark.renderer]
    hardWraps = true
