# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Graphy"
license = "Apache 2.0"
licenselink = "https://github.com/learninfun/hugo-graphy/blob/main/LICENSE"
description = "Documentation theme for Hugo, based on Hugo Learn theme"
homepage = "https://github.com/learninfun/hugo-graphy/"
repo = "https://github.com/matcornic/hugo-theme-learn"
tags = ["documentation", "learn", "doc", "search", "graphy"]
features = ["documentation", "menu", "nested sections", "search", "mermaid"]
min_version = 0.25

[author]
  name = "Brad Huang"

[original]
  name = "Hugo Learn theme"
  homepage = "https://learn.netlify.app/"
  repo = "https://github.com/matcornic/hugo-theme-learn"
